### ISSUE TITLE
Error when setting regression=False

### ISSUE THREAD

**Issue by ZebinYang** [BillHuang01/first#1]
https://github.com/BillHuang01/pyfirst/blob/695c05fcbfca8f4e85d964bc57cc5948237b937c/src/pyfirst/pyfirst.py#L653

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by BillHuang01** [comment]
Thanks for raising this bug! The issue is resolved in the new release version 0.1.4.

**Comment by BillHuang01** [comment]
Thanks for raising this bug! The issue is resolved in the new release version 0.1.4.
